version: '1.0'

services:
  web:
    build: ./services/web
    command: python3 -m flask --app weereg run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:8-debian
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=weewx
      - MYSQL_PASSWORD=weewx
      - MYSQL_DB=weereg_dev

volumes:
  mysql_data:
